"""add_cv_fields

Revision ID: 13d11307588a
Revises: 4a16a9b9a554
Create Date: 2025-06-20 00:45:20.701419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d11307588a'
down_revision: Union[str, None] = '4a16a9b9a554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_uploaded_cv', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('cv_filename', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cv_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cv_upload_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cv_upload_date')
    op.drop_column('users', 'cv_path')
    op.drop_column('users', 'cv_filename')
    op.drop_column('users', 'has_uploaded_cv')
    # ### end Alembic commands ###
