"""Add has_preferences_data flag to users table

Revision ID: 3d7205a6842b
Revises: 8dbb983e260f
Create Date: 2025-06-24 06:22:32.787019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7205a6842b'
down_revision: Union[str, None] = '8dbb983e260f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_preferences_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_preferences_data')
    # ### end Alembic commands ###
