"""Add work preferences table

Revision ID: 8dbb983e260f
Revises: 0fe7201f24d1
Create Date: 2025-06-24 05:49:45.114325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbb983e260f'
down_revision: Union[str, None] = '0fe7201f24d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expected_salary', sa.Enum('RANGE_5K', 'RANGE_10K', 'RANGE_15K', 'RANGE_20K', name='salaryrange'), nullable=False),
    sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'FREELANCE', name='jobtype'), nullable=False),
    sa.Column('desired_role', sa.String(), nullable=False),
    sa.Column('industries', sa.String(), nullable=False),
    sa.Column('willing_to_relocate', sa.Enum('YES_WITH_SUPPORT', 'YES_WITHOUT_SUPPORT', 'NO', name='relocationpreference'), nullable=False),
    sa.Column('remote_work_preference', sa.Enum('HYBRID', 'REMOTE_ONLY', 'ONSITE_ONLY', name='remotepreference'), nullable=False),
    sa.Column('years_of_experience', sa.Enum('ZERO_TO_TWO', 'THREE_TO_FIVE', 'FIVE_PLUS', 'TEN_PLUS', name='experiencelevel'), nullable=False),
    sa.Column('notice_period', sa.Enum('IMMEDIATE', 'ONE_WEEK', 'TWO_WEEKS', 'ONE_MONTH', 'TWO_MONTHS', name='noticeperiod'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_work_preferences_id'), 'work_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_preferences_id'), table_name='work_preferences')
    op.drop_table('work_preferences')
    # ### end Alembic commands ###
